add_lora: true
alpha: 0.9
batch_size: 64
beta: 0.999
bias_lr_factor: 2.0
dataset_name: ORBench
distributed: false
eval_period: 20
freeze_vision_encoder: false
gamma: 0.1
id_loss_weight: 1.0
img_aug: true
img_size: !!python/tuple
- 384
- 128
local_rank: 0
log_period: 50
lora_layers: 12
lora_lr_factor: 5.0
lora_mode: all
lora_r: 4
loss_names: mm_sdm+id
lr: 1.0e-05
lrscheduler: cosine
milestones: !!python/tuple
- 20
- 50
mmt_depth: 1
momentum: 0.9
name: reid5o_ckpt
num_epoch: 60
num_instance: 4
num_loras: 4
num_workers: 8
optimizer: Adam
output_dir: logs/reid5o_ckpt
power: 0.9
pretrain_choice: ViT-B/16
resume: false
resume_ckpt_file: ''
root_dir: /data/970ep/jlongzuo
sampler: random
stride_size: 16
target_lr: 0
temperature: 0.02
test_batch_size: 512
text_length: 77
training: true
val_dataset: test
vocab_size: 49408
warmup_epochs: 5
warmup_factor: 0.1
warmup_method: linear
weight_decay: 4.0e-05
weight_decay_bias: 0.0